#!/bin/sh

xwallpaper --zoom ~/.local/share/bg.jpg

xrdb -merge ~/.Xresources

xbacklight -set 70 &

xset r rate 210 40

picom --config /home/stoney/.config/picom/picom.conf &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

nm-applet &

sxhkd &

# ~/.local/src/suckless/dwm/scripts/bar.sh &

~/.local/bin/battery.sh &

exec slstatus &

# 2 is stderr file descriptor
exec dwm 2>"$HOME/.cache/dwm.log"
